export const HOME_VIDEOS_SUCCESS="HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_REQUEST="HOME_VIDEOS_REQUEST";
export const HOME_VIDEOS_FAIL="HOME_VIDEOS_FAIL";



export const SELECTED_VIDEOS_SUCCESS="SELECTED_VIDEOS_SUCCESS";
export const SELECTED_VIDEOS_REQUEST="SELECTED_VIDEOS_REQUEST";
export const SELECTED_VIDEOS_FAIL="SELECTED_VIDEOS_FAIL";


export const COMMENT_LIST_SUCCESS="COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_REQUEST="COMMENT_LIST_REQUEST";
export const COMMENT_LIST_FAIL="COMMENT_LIST_FAIL";



export const SEARCHED_VIDEOS_SUCCESS="SEARCHED_VIDEOS_SUCCESS";
export const SEARCHED_VIDEOS_REQUEST="SEARCHED_VIDEOS_REQUEST";
export const SEARCHED_VIDEOS_FAIL="SEARCHED_VIDEOS_FAIL";


export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_OUT="LOGIN_OUT";
export const LOAD_PROFILE="LOAD_PROFILE";
